//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bdeli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bD_Booking
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string DateBooking { get; set; }
        public string TimeBooking { get; set; }
        public string Amount { get; set; }
        public string Note { get; set; }
        public string Tel { get; set; }
    }
}
