//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bdeli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bD_OpenTime
    {
        public int id { get; set; }
        public string mon { get; set; }
        public string tue { get; set; }
        public string wen { get; set; }
        public string thu { get; set; }
        public string fri { get; set; }
        public string sat { get; set; }
        public string sun { get; set; }
        public string monend { get; set; }
        public string tueend { get; set; }
        public string wenend { get; set; }
        public string thuend { get; set; }
        public string friend { get; set; }
        public string satend { get; set; }
        public string sunend { get; set; }
    }
}
