//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bdeli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bD_Service
    {
        public int id { get; set; }
        public string Images1 { get; set; }
        public string Title1 { get; set; }
        public string Description1 { get; set; }
        public string Images2 { get; set; }
        public string Title2 { get; set; }
        public string Description2 { get; set; }
        public string Images3 { get; set; }
        public string Title3 { get; set; }
        public string Description3 { get; set; }
    }
}
