//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bdeli.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bDeliEntities : DbContext
    {
        public bDeliEntities()
            : base("name=bDeliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bD_Booking> bD_Booking { get; set; }
        public virtual DbSet<bD_Contact> bD_Contact { get; set; }
        public virtual DbSet<bD_Food> bD_Food { get; set; }
        public virtual DbSet<bD_FoodType> bD_FoodType { get; set; }
        public virtual DbSet<bD_Gift> bD_Gift { get; set; }
        public virtual DbSet<bD_Images> bD_Images { get; set; }
        public virtual DbSet<bD_Introduce> bD_Introduce { get; set; }
        public virtual DbSet<bD_OpenTime> bD_OpenTime { get; set; }
        public virtual DbSet<bD_Service> bD_Service { get; set; }
        public virtual DbSet<bD_Slide> bD_Slide { get; set; }
        public virtual DbSet<bD_TypeGift> bD_TypeGift { get; set; }
        public virtual DbSet<bD_Video> bD_Video { get; set; }
    }
}
